COMPONENT=DemoAppC
CFLAGS += -I$(HOME)/tinyos-main/tos/lib/printf

#TINYOS_ROOT_DIR?=../../..
#include $(TINYOS_ROOT_DIR)/Makefile.include


## LRJ troubleshooting below
#SENSORBOARD=telosb

#TINYOS_ROOT_DIR?=../../../../../..
TINYOS_ROOT_DIR?=/home/liam/tinyos-main/support/sdk/java
include $(TINYOS_ROOT_DIR)/Makefile.include
$(MAKERUlES)
